name: Log MSBuild Path

on:
  push:
    branches:
      - main

jobs:
  log-msbuild-path:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log MSBuild Path
        run: |
          # Check the default MSBuild installation path for Visual Studio Enterprise
          $msbuildPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe"

          if (Test-Path $msbuildPath) {
            Write-Host "MSBuild is found at: $msbuildPath"
          } else {
            Write-Host "MSBuild not found at the expected path."
          }
