name: Build AdvanceSetup MSI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Advanced Installer
        run: choco install advanced-installer --version=20.3.1 --yes

      - name: Locate and Set Advanced Installer Path
        id: locate-ai
        run: |
          # Locate the Advanced Installer directory
          $installerDir = Get-ChildItem "C:\Program Files (x86)\Caphyon\Advanced Installer*" -Directory | Sort-Object LastWriteTime -Descending | Select-Object -ExpandProperty FullName -First 1
          
          # Confirm the installation and set path if found
          if (Test-Path "$installerDir\bin\x86\AdvancedInstaller.com") {
            echo "AdvancedInstaller.com found at $installerDir\bin\x86"
            echo "ADVANCED_INSTALLER_PATH=$installerDir\bin\x86" >> $GITHUB_ENV
          } else {
            Write-Error "AdvancedInstaller.com not found in expected directory: $installerDir\bin\x86"
            exit 1
          }

      - name: Confirm Path Environment Variable
        run: |
          Write-Output "ADVANCED_INSTALLER_PATH is set to: $env:ADVANCED_INSTALLER_PATH"
          if (-not (Test-Path "$env:ADVANCED_INSTALLER_PATH\AdvancedInstaller.com")) {
            Write-Error "AdvancedInstaller.com executable not found in path: $env:ADVANCED_INSTALLER_PATH"
            exit 1
          }

      - name: Build MSI using Advanced Installer
        run: |
          $env:Path += ";$env:ADVANCED_INSTALLER_PATH"
          Write-Output "Using AdvancedInstaller.com from: $env:ADVANCED_INSTALLER_PATH"
          &"$env:ADVANCED_INSTALLER_PATH\AdvancedInstaller.com" /build AdvanceSetup/AdvanceSetup.aip

      - name: Upload AdvanceSetup.msi artifact
        uses: actions/upload-artifact@v3
        with:
          name: AdvanceSetup
          path: AdvanceSetup/AdvanceSetup-SetupFiles/AdvanceSetup.msi
