name: Build Setup Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; 
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; 
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Install Visual Studio 2019 Community
        run: |
          choco install visualstudio2019community --params "--add Microsoft.VisualStudio.Workload.ManagedDesktop --includeRecommended --includeOptional --quiet --norestart"

      - name: Set Visual Studio Path
        id: set_vspath
        run: |
          $vsPath = & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath
          echo "vs_installation_path=$vsPath" >> $GITHUB_ENV
          echo "Visual Studio installed at: $vsPath"

      - name: Restore NuGet packages
        run: |
          nuget restore ./WinformsGithubActions.sln

      - name: Build the solution
        run: |
          & "$env:vs_installation_path\MSBuild\Current\Bin\MSBuild.exe" ./WinformsGithubActions.sln /p:Configuration=Release

      - name: Build Setup Project
        run: |
          & "$env:vs_installation_path\Common7\IDE\devenv.exe" ".\Setup\Setup.vdproj" /Build Release

      - name: Upload .msi as artifact
        uses: actions/upload-artifact@v3
        with:
          name: SetupMSI
          path: ./Setup/Release/WinformsGithubActions Installer.msi # Adjust this path if needed to match the actual output directory
