name: Build Setup Project

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v1
              with:
                  vs-version: "16.0" # Use Visual Studio 2019

            - name: Restore NuGet packages
              run: |
                  nuget restore ./WinformsGithubActions.sln

            - name: Build the solution
              run: |
                  & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" "./WinformsGithubActions.sln" /p:Configuration=Release

            - name: Upload .msi as artifact
              uses: actions/upload-artifact@v3
              with:
                  name: SetupMSI
                  path: ./Setup/Release/WinformsGithubActions Installer.msi # Adjust this path if needed to match the actual output directory
