name: Build AdvanceSetup MSI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Advanced Installer
        run: choco install advanced-installer --version=20.3.1 --yes

      - name: Build MSI using Advanced Installer
        shell: pwsh
        run: |
          # Define the direct path to AdvancedInstaller.com
          $advancedInstallerPath = 'C:\Program Files (x86)\Caphyon\Advanced Installer 20.3.1\bin\x86\AdvancedInstaller.com'
          
          # Confirm AdvancedInstaller.com exists at this path
          if (-not (Test-Path $advancedInstallerPath)) {
            Write-Error "AdvancedInstaller.com executable not found in path: $advancedInstallerPath"
            exit 1
          }

          # Display contents of the Advanced Installer directory for debugging
          Write-Output "Contents of Advanced Installer directory:"
          Get-ChildItem "C:\Program Files (x86)\Caphyon\Advanced Installer 20.3.1\bin\x86" | Write-Output

          # Run the build command directly using the full path
          Write-Output "Using AdvancedInstaller.com from: $advancedInstallerPath"
          & "$advancedInstallerPath" /build AdvanceSetup/AdvanceSetup.aip

      - name: Upload AdvanceSetup.msi artifact
        uses: actions/upload-artifact@v3
        with:
          name: AdvanceSetup
          path: AdvanceSetup/AdvanceSetup-SetupFiles/AdvanceSetup.msi
