name: Build Setup Project

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: windows-2019

        steps:
            # Step 1: Checkout the code
            - name: Checkout code
              uses: actions/checkout@v2

            # Step 2: Download Visual Studio Installer
            - name: Download Visual Studio Build Tools Installer
              run: |
                  Invoke-WebRequest -Uri "https://aka.ms/vs/16/release/vs_buildtools.exe" -OutFile "vs_installer.exe"

            # Step 3: Install Visual Studio Build Tools with required components
            - name: Install Visual Studio Build Tools
              run: |
                  .\vs_installer.exe --quiet --wait --norestart --installPath "C:\BuildTools" --add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.ComponentGroup.NativeDesktop.WinXP --add Microsoft.VisualStudio.Component.VC.CLI.Support --add Microsoft.VisualStudio.Component.VC.Tools.ARM64 --add Microsoft.VisualStudio.Component.Windows10SDK.19041 --includeRecommended --includeOptional

            # Step 4: Restore NuGet packages
            - name: Restore NuGet packages
              run: |
                  nuget restore ./WinformsGithubActions.sln

            # Step 5: Build the solution using devenv
            - name: Build the solution
              run: |
                  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.com" D:\a\WinformsGithubActions\WinformsGithubActions\WinformsGithubActions.sln /Build "Release"

            # Step 6: Upload the MSI file generated from the setup project
            - name: Upload .msi as artifact
              uses: actions/upload-artifact@v3
              with:
                  name: SetupMSI
                  path: ./Setup/Release/WinformsGithubActions.msi # Adjust this path if needed to match the actual output directory
