name: Check Visual Studio Workload

on:
  push:
    branches:
      - main

jobs:
  check-visual-studio-workload:
    runs-on: windows-2019

    steps:
      - name: Check Visual Studio Workload
        run: |
          # Define the path to vswhere
          $vsInstallPath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"

          # Check if vswhere exists
          if (Test-Path $vsInstallPath) {
              # Get the installed Visual Studio versions in JSON format
              $vsInfo = & $vsInstallPath -products * -format json

              # Convert JSON output to PowerShell objects
              $vsVersions = $vsInfo | ConvertFrom-Json

              # Check if any versions are found
              if ($vsVersions) {
                  foreach ($version in $vsVersions) {
                      Write-Host "Version: $($version.version), Path: $($version.installationPath)"

                      # Check for installed workloads
                      $workloads = $version.installationPath + '\Common7\IDE\devenv.exe' + ' /Log'
                      $workloadInfo = & $workloads

                      if ($workloadInfo -match "Microsoft.VisualStudio.Workload.ManagedDesktop") {
                          Write-Host "The 'Desktop development with .NET' workload is installed."
                      } else {
                          Write-Host "The 'Desktop development with .NET' workload is NOT installed."
                      }
                  }
              } else {
                  Write-Host "No Visual Studio installations found."
              }
          } else {
              Write-Host "vswhere.exe not found. Visual Studio might not be installed."
          }
