name: Build Setup Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Visual Studio Build Tools Installer
        run: |
          Invoke-WebRequest -Uri "https://aka.ms/vs/16/release/vs_buildtools.exe" -OutFile "vs_installer.exe"

      - name: Install Visual Studio Installer Projects Extension
        run: |
          .\vs_installer.exe --quiet --wait --norestart `
          --installPath "C:\BuildTools" `
          --add Microsoft.VisualStudio.ComponentGroup.VC.Tools.x86.x64 `
          --add Microsoft.VisualStudio.Component.VC.CLI.Support `
          --add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools `
          --add Component.Microsoft.VisualStudio.RazorExtension `
          --add Microsoft.VisualStudio.Component.VC.Tools.ARM64

      - name: Restore NuGet packages
        run: |
          nuget restore ./WinformsGithubActions.sln

      - name: Build the Setup Project
        run: |
          Start-Process -FilePath "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.com" `
          -ArgumentList '"D:\a\WinformsGithubActions\WinformsGithubActions\WinformsGithubActions.sln" /Build "Release|Any CPU"' `
          -Verb RunAs -NoNewWindow -Wait

      - name: Upload .msi as artifact
        uses: actions/upload-artifact@v3
        with:
          name: SetupMSI
          path: ./Setup/Release/WinformsGithubActions.msi
