name: Build Setup Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: "16.0" # Specify the Visual Studio version you need (16.0 for VS2019)

      - name: Check for Visual Studio
        id: check_vs
        run: |
          if (!(Test-Path "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe")) {
            echo "vswhere.exe not found, installing Visual Studio..."
            choco install visualstudio2019community --params "--add Microsoft.VisualStudio.Workload.ManagedDesktop --includeRecommended --includeOptional --quiet --norestart"
          } else {
            $vsInstance = & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
            if ($null -eq $vsInstance) {
              echo "Visual Studio not found, installing..."
              choco install visualstudio2019community --params "--add Microsoft.VisualStudio.Workload.ManagedDesktop --includeRecommended --includeOptional --quiet --norestart"
            } else {
              echo "Visual Studio is already installed at: $vsInstance"
              # Set the installation path for later use
              echo "vs_installation_path=$vsInstance" >> $GITHUB_ENV
            }
          }

      - name: Restore NuGet packages
        run: |
          nuget restore ./WinformsGithubActions.sln

      - name: Build the solution
        run: |
          msbuild ./WinformsGithubActions.sln /p:Configuration=Release

      - name: Check for devenv.exe
        run: |
          $vsPath = "${{ env.vs_installation_path }}"
          if (Test-Path "$vsPath\Common7\IDE\devenv.exe") {
              echo "devenv.exe found at $vsPath\Common7\IDE\devenv.exe"
          } else {
              echo "devenv.exe not found at $vsPath\Common7\IDE\devenv.exe"
              exit 1 # Exit with error if devenv.exe is not found
          }

      - name: Build Setup Project
        run: |
          $vsPath = "${{ env.vs_installation_path }}"
          & "$vsPath\Common7\IDE\devenv.exe" ".\Setup\Setup.vdproj" /Build Release

      - name: Upload .msi as artifact
        uses: actions/upload-artifact@v3
        with:
          name: SetupMSI
          path: ./Setup/Release/WinformsGithubActions Installer.msi # Adjust this path if needed to match the actual output directory
