name: Build Setup Project

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v1
              with:
                  vs-version: "16.0" # Visual Studio version (16.0 for VS2019)

            - name: Build Setup Project
              run: |
                  msbuild ./Setup/Setup.vdproj /p:Configuration=Release /p:Platform=x86

            - name: Upload .msi as artifact
              uses: actions/upload-artifact@v3
              with:
                  name: SetupMSI
                  path: ./Setup/Release/*.msi # Adjust the path if necessary
