name: Build Setup Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Visual Studio Build Tools
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.VC.Redist.14.Latest --includeRecommended --includeOptional" --no-progress

      - name: Restore NuGet packages
        run: nuget restore ./WinformsGithubActions.sln

      - name: Build the solution
        run: |
          msbuild ./WinformsGithubActions.sln /p:Configuration=Release

      - name: Build Setup project using devenv
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.com" D:\a\WinformsGithubActions\WinformsGithubActions.sln /Build "Release"

      - name: Upload .msi as artifact
        uses: actions/upload-artifact@v3
        with:
          name: SetupMSI
          path: ./Setup/Release/*.msi  # Adjust this path if needed to match the actual output directory
