name: Build AdvanceSetup MSI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Advanced Installer
        if: ${{ !env.ADVANCED_INSTALLER_PATH }}
        run: |
          choco install advanced-installer --version=20.3.1 --yes
          echo "ADVANCED_INSTALLER_PATH=C:\Program Files (x86)\Caphyon\Advanced Installer 20.3.1\bin\x86" >> $GITHUB_ENV

      - name: Cache Advanced Installer dependencies
        uses: actions/cache@v3
        with:
          path: AdvanceSetup/AdvanceSetup-cache
          key: ${{ runner.os }}-advanced-installer-cache
          restore-keys: |
            ${{ runner.os }}-advanced-installer-cache

      - name: Build MSI using Advanced Installer
        run: |
          $env:Path += ";$env:ADVANCED_INSTALLER_PATH"
          &"$env:ADVANCED_INSTALLER_PATH\AdvancedInstaller.com" /build AdvanceSetup/AdvanceSetup.aip

      - name: Upload AdvanceSetup.msi artifact
        uses: actions/upload-artifact@v3
        with:
          name: AdvanceSetup
          path: AdvanceSetup/AdvanceSetup-SetupFiles/AdvanceSetup.msi
