name: Build AdvanceSetup MSI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Advanced Installer
        run: choco install advanced-installer --version=20.3.1 --yes

      - name: Set Advanced Installer Path Directly
        run: |
          # Directly set the path to the known Advanced Installer location
          echo "ADVANCED_INSTALLER_PATH=C:\Program Files (x86)\Caphyon\Advanced Installer 20.3.1\bin\x86" >> $GITHUB_ENV

      - name: Confirm Path Environment Variable and Directory Contents
        run: |
          # Check and display the ADVANCED_INSTALLER_PATH environment variable
          Write-Output "ADVANCED_INSTALLER_PATH is set to: $env:ADVANCED_INSTALLER_PATH"
          if ($env:ADVANCED_INSTALLER_PATH -eq $null) {
            Write-Error "ADVANCED_INSTALLER_PATH is not set."
            exit 1
          }

          # Display the contents of ADVANCED_INSTALLER_PATH to verify it contains AdvancedInstaller.com
          Write-Output "Contents of $env:ADVANCED_INSTALLER_PATH:"
          Get-ChildItem "$env:ADVANCED_INSTALLER_PATH" | Write-Output
          
          if (-not (Test-Path "$env:ADVANCED_INSTALLER_PATH\AdvancedInstaller.com")) {
            Write-Error "AdvancedInstaller.com executable not found in path: $env:ADVANCED_INSTALLER_PATH"
            exit 1
          }

      - name: Build MSI using Advanced Installer
        run: |
          # Append ADVANCED_INSTALLER_PATH to system PATH
          $env:Path += ";$env:ADVANCED_INSTALLER_PATH"
          Write-Output "Using AdvancedInstaller.com from: $env:ADVANCED_INSTALLER_PATH"
          &"$env:ADVANCED_INSTALLER_PATH\AdvancedInstaller.com" /build AdvanceSetup/AdvanceSetup.aip

      - name: Upload AdvanceSetup.msi artifact
        uses: actions/upload-artifact@v3
        with:
          name: AdvanceSetup
          path: AdvanceSetup/AdvanceSetup-SetupFiles/AdvanceSetup.msi
