name: Build WinForms Application

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v1
              with:
                  vs-version: "16.0" # Specify the Visual Studio version you need (16.0 for VS2019)

            - name: Restore NuGet packages
              run: |
                  nuget restore ./WinformsGithubActions.sln

            - name: Build the project
              run: |
                  msbuild ./WinformsGithubActions/WinformsGithubActions.csproj /p:Configuration=Release

            - name: Upload WinformsGithubActions.exe
              uses: actions/upload-artifact@v3
              with:
                  name: WinformsGithubActions
                  path: ./WinformsGithubActions/bin/Release/WinformsGithubActions.exe
