name: Build Setup Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019  # Using windows-2019 runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: "16.0" # Specify the Visual Studio version you need (16.0 for VS2019)

      - name: Install Required Visual Studio Components
        run: |
          # Check if the required components are installed
          $requiredComponents = @(
              "Microsoft.VisualStudio.Workload.ManagedDesktop"  # Add any other required components here
          )
          
          $missingComponents = @()
          foreach ($component in $requiredComponents) {
              $installed = & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\vswhere.exe" -products * -requires $component -property installLocation
              if (-Not $installed) {
                  $missingComponents += $component
              }
          }

          if ($missingComponents.Count -gt 0) {
              Write-Host "Missing components found: $($missingComponents -join ', '), installing..."
              choco install visualstudio2019community --params "--add $($missingComponents -join ',') --includeRecommended --includeOptional"
          } else {
              Write-Host "All required components are already installed."
          }
        shell: pwsh

      - name: Restore NuGet packages
        run: |
          nuget restore ./WinformsGithubActions.sln

      - name: Build the solution
        run: |
          msbuild ./WinformsGithubActions.sln /p:Configuration=Release

      - name: Build Setup Project
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.exe" ./Setup/Setup.vdproj /Build Release

      - name: Upload .msi as artifact
        uses: actions/upload-artifact@v3
        with:
          name: SetupMSI
          path: ./Setup/Release/WinformsGithubActions Installer.msi # Adjust this path if needed to match the actual output directory
