name: Build and Upload WinformsGithubActions Project

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install NuGet dependencies
              run: nuget restore ./WinformsGithubActions.sln

            - name: Find MSBuild Path
              run: |
                  echo "Finding MSBuild..."
                  $msbuildPath = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
                  echo "MSBuild found at: $msbuildPath"
                  echo "##vso[task.setvariable variable=MSBUILD_PATH]$msbuildPath"

            - name: Build WinformsGithubActions project
              run: |
                  $env:MSBUILD_PATH ./WinformsGithubActions/WinformsGithubActions.csproj /p:Configuration=Release

            - name: Upload WinformsGithubActions.exe as artifact
              uses: actions/upload-artifact@v3
              with:
                  name: WinformsGithubActions-exe
                  path: WinformsGithubActions/bin/Release/WinformsGithubActions.exe
