name: Build AdvanceSetup MSI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Advanced Installer
        run: |
          choco install advanced-installer --version=22.1 --yes
          if (!(Get-Command AdvancedInstaller.com -ErrorAction SilentlyContinue)) {
            Write-Error "Advanced Installer failed to install."
            exit 1
          }

      - name: Build MSI using Advanced Installer
        shell: pwsh
        run: |
          $advancedInstallerPath = 'C:\Program Files (x86)\Caphyon\Advanced Installer 22.1\bin\x86\AdvancedInstaller.com'

          if (-not (Test-Path $advancedInstallerPath)) {
            Write-Error "AdvancedInstaller.com executable not found in path: $advancedInstallerPath"
            exit 1
          }

          Write-Output "Using AdvancedInstaller.com from: $advancedInstallerPath"
          & "$advancedInstallerPath" /build AdvanceSetup/AdvanceSetup.aip

      - name: Upload AdvanceSetup.msi artifact
        uses: actions/upload-artifact@v3
        with:
          name: AdvanceSetup
          path: AdvanceSetup/AdvanceSetup-SetupFiles/AdvanceSetup.msi
