name: Build Setup Project

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: windows-2019

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v1
              with:
                  vs-version: "16.0"  # Specify the Visual Studio version you need (16.0 for VS2019)

            - name: Clean the solution
              run: |
                  & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.com" "D:\a\WinformsGithubActions\WinformsGithubActions\WinformsGithubActions.sln" /Clean "Release"

            - name: Build the solution
              run: |
                  & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.com" "D:\a\WinformsGithubActions\WinformsGithubActions\WinformsGithubActions.sln" /Build "Release" /Log "build.log" /verbosity:diagnostic"

            - name: Upload .msi as artifact
              uses: actions/upload-artifact@v3
              with:
                  name: SetupMSI
                  path: ./Setup/Release/*.msi  # Adjust this path if needed to match the actual output directory
